### ISSUE TITLE
Bitbucket repo throws TypeError

### ISSUE THREAD

**Issue by SunflowerFuchs** [sindresorhus/gh-home#6]
```
TypeError: Expected a `target`
at module.exports (/home/developer/.nvm/versions/node/v9.3.0/lib/node_modules/gh-home/node_modules/open/index.js:18:9)
at __dirname (/home/developer/.nvm/versions/node/v9.3.0/lib/node_modules/gh-home/cli.js:45:9)
at <anonymous>
```

Not exactly an important issue since it's not github anyway, but maybe it should at least fail gracefully.

**Comment by sindresorhus** [comment]
Yeah, could be nicer handled. PR welcome.
